### ISSUE TITLE
Thoughts, improvements and discussion

### ISSUE THREAD

**Issue by sausix** [kbr/autocron#1]
Interesting project. I didn't run it yet and also didn't test edge cases. May be some of my points are not really relevant.

SQlite does not recommend multiple processes writing to the same database file. Since the project is flagged as multi platform, a lot of pitfalls are waiting for the users.
[SQLite FAQ#5](https://www.sqlite.org/faq.html#q5)
Are the squlite3 connections optimized? Isn't `journal_mode=WAL` an option and other flags?
Is it on purpose you use a new sqlite connection on each _execute call?
A lot of sqlite calls are not handled. An exception could crash the whole worker, which can be avoided.

The interface/backend for autocron should be a proper interface and sqlite a single implementation in a subfolder.
By having a proper interface, you can also compare and run tests for different backends.
What about some magic like this?
```python
from autocron.engine_backends import sqlite_backend
backend = sqlite_backend("the_flask_app.db")
autocron.start(backend)
```

My first implementation recommendation would be a single backend Python process which easily communicates though pipes or even stdin/stdout. Or sockets for unix if they're more performant. The backend could just talk to its managed worker processes.

What about hanging tasks? No timeout supported?
Explicit rules on task exceptions? Retry, a callback function, cancel repeating tasks?
What happens to error_message? It's being written to the database and then? How to get it?
Overlapping tasks? Running a task every second which runs longer than a second? Explicit behaviour by the decorator with implicit default as argument.
How can I later check the result of a task? Offer a handle the get information. Maybe I'm interested in the function result on another page if it has successfully completed.

Since we are using Python and not a decades old syntax, the old notation "* * * * *" should be the *second* choice.
It would be also easier to just split into two explicit decorators. For usage and for implementation. For example:
```python
@autocron.cron_str("* * * * *")
@autocron.cron_kw(hours=1, minutes=2)
```
Just keep `autocron.cron` as proxy which delegates to the correct function.

```
def cron( ...
:minutes:
        list of minutes ...
``` 
It's not (always) a list of minutes obviously. And you could easily add support for "*/5" syntax to make it 100% cron compatible.
This should work but it is not supported:
```python
c = CronScheduler(hours=5, minutes="10-20", dom="2,3,5")
```
Since there are special rules that only fit into a string, `minutes=[1,2,3]` format should be a secondary choice.

The used "Sequencer" in class attributes is not really necessary. Why not simply checking the arguments within \_\_init__ with the help of functions?
What if I supply the crontab argument and one of the others? Or I pass "* * * * * * * * * *"? Or anything else invalid? The tests should also cover invalid definitions to test data validation.

Classic crontab defines 0=Sunday, 1=Monday, .... You just changed this behaviour to 0=Monday and your cron implementation loses compatibility. Why not following the standard and just offer an optionaly switch?

`if not any(locals().values()):`
Very hacky. Why not just passing all arguments right into the `CronScheduler.__init__` and raise an exception if something's wrong? It can create a dummy CronScheduler instance early at "decorator time" so you get syntax problems earlier.

What about autocron access without decorators?
Just addressing a function with specific arguments? What about seconds and specific seconds? Remember, we are in Python, not in a shell. Should be possible to place a task on second=30 for example.
Or someone wants to call a decorated functions right now in the main thread? Like this:
```python
@autocron.cron("1 2 3 * *")
def my_cronjob():
    # do something from time to time ...

def anywhere_anytime():
    my_cronjob.run_in_sync_now()  # I want it now!
```

Also the `delay` decorator is misleading. It does not delay in first place. People could excpect a seconds attribute. A proper name for this decorator could be "background_exec", "run_async" or similar. What if I want a function be called in 20 seconds? Install another package? autocron could easily support this by a third decorator.

What about logging? What are the workers doing? Could be important if something fails. Just use the logging module for output and tracking.

Don't use setattr, getattr internally until you have a good reason. Also don't use SimpleNamespace. Or even a subclass of SimpleNamespace just to have additional dict access for no reason.
Use appropriate data types. named tuples, dataclasses or even very specific classes. Use references and connect schedules to tasks etc. Use common classes between the scheduler and the workers so pickling is easy and transparent.

Your `HybridNamespace.__init__` does not call its parent class' `__init__`. A proper IDE should throw a warning here. Mine does.
You don't have to use PyCharm, but at least open your projects with it to directly see problems and warnings. Pylint does not catch all problems and PyCharm also finds some flaws in too much or too less spaces and unsafe logic.
Logic like your `if not self.dow and not self.dom:` chain should always default into an `else:` branch. Even if your logic works now. Instead of 4x condition checking reduce it into 3x checking and an else branch.
Tools then also can better check if your "schedule" variable is really defined before handing it over to return.

Why does `get_next_schedule` has only month specific logic? month_allowed, set_allowed_month... Comments should explain. I don't understand and you will probably don't understand your code either in a couple of months or years.

`find_next_schedule`: A lot of complex and repetitive code. Also `get_next_schedule` has a similar name which is confusing. Maybe combine them?

`ls = last_schedule` Don't. And you don't have to if your code doesn't repeat a lot. And don't just turn off pylint warnings just because they're annoying.

Please start using typing and annotations. At least users of autocron will be helped a lot knowing allowed argument types. And it will help YOU a lot during coding. Your IDE doesn't know which data types are expected in lists for example. Typing an annotating is fun and helps a lot. You also don't specify types in docstrings. Please don't prefer being old school. Solid code make you a better programmer. Not just being able to code without a proper IDE. IDEs offer much more than only code coloring and completion.

**Comment by kbr** [comment]
Thank you for the thoughts. At the meeting in Düsseldorf, where you have attended, I have presented this project for the first time in public and the choice for SQLite was explained. The limitations of SQLite are known and also how to access results have been shown in short.

It seems to be important to emphasize again that the project aims for simplicity for the user and not as a celery replacement. The public API is about two decorators and one method call – and I will keep it this way.

The SQLite limitations may be overcome with an optional use of PostgreSQL or MySQL in the future. Optional, because the SQLite based version in its current implementation is already good enough for a lot of use cases even without further optimisations.

Some remarks about the CronScheduler class are right, but what you should know: this is legathy code imported from a preceding project (also mentioned in the talk) dated back from more than 10 years ago. It is tested and works reliable since then in production in combination with the 'Sequencer' descriptor and that is fine for the moment. 

There is a lot more about design descisions that are best discussed at meetings to avoid missunderstandings and to not get lost in details or alternate ways of doing things. 

Please keep in mind that a lot of ``pylint`` reportings are not annyoing but opinionated and that parts of the advanced features of IDEs are provided by language servers which are also integrable in "pure" programming editors.

On this occasion I want to give some advice for everyone who likes to contribute to this project:

- readability counts (Zen of Python)
- write tests (currently switching from unittest to pytest)
- no type hints (pros and cons known)

I should put this into ``CONTRIBUTING.md`` next time.

**Comment by sausix** [comment]
> and the choice for SQLite was explained.

Because redis did not work for you? You did not mention write locks in the talk. I wanted to look into the code before discussing first.


> It seems to be important to emphasize again that the project aims for simplicity for the user and not as a celery replacement.

It can stay simple as it is. With the same syntax and with optional arguments to allow different backends. A project should primarily work.


> Optional, because the SQLite based version in its current implementation is already good enough for a lot of use cases even without further optimisations.

Did you test that? I don't see any exception handling, tests or logging in your code for database access. If may work in your own browser demonstrations but you can hit the write lock with only two users already if they're timed unfortunately.  
You're just guessing this project is "good enough" and you don't address basic things like i mentioned. It looks like small projects don't need reliability.

> this is legathy code imported from a preceding project (also mentioned in the talk) dated back from more than 10 years ago

Is this project for internal PyDDF use only? Do people have to join the talks before using this project? Put information like this in the primary README.md. Also that it's a remake of an older project.

> in combination with the 'Sequencer' descriptor and that is fine for the moment.

You're using class attribute descriptors for advanced use cases for a simple task. What about keep it simple? Zen of Python?

> There is a lot more about design descisions that are best discussed at meetings

How did other projects grow without meetings? Do you only expect contributions from PyDDF attendees?

> Please keep in mind that a lot of pylint reportings are not annyoing but opinionated

Yes. I allowing longer lines for my projects. That's almost it. But I don't claim my projects are Pylint conform and then add a bunch of exceptions.

I've looked at the first pylint exception in autocron:
```python
        # here is pylint wrong:
        # pylint: disable=unnecessary-lambda
        column_width = len(max(keys, key=lambda x: len(x)))
```
You're basically claiming you are right and pylint is wrong. But you could just have used `key=len` instead. But I'm already sure you will claim to have pros for that decision. Probably you just like it this way.

> On this occasion I want to give some advice for everyone who likes to contribute to this project:

Since you silently ignored most of my considerations and probably never address them in your project, it does not feel like you want to have help or contributions.

So I'm just wasting my time here.

**Comment by kbr** [comment]
> How did other projects grow without meetings? Do you only expect contributions from PyDDF attendees?


That's easy to explain. You have fired such an amount of topics, questions and never requested suggestions that talks are best to keep everything back on track.

> But you could just have used ``key=len`` instead.

Yes indeed, why didn't you mentioned this as an issue right at the beginning? Btw. I have never claimed that the project is "Pylint conform".

I close this as I suppose the issue should look helpfull at first but was never intended to be. Proof me wrong. Until then I want to prevent you from wasting even more time.
