### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by jedie** [kbr/autocron#3]
I get on startup just:

```
  File "/home/jens/repos/django-for-runners/for_runners/apps.py", line 12, in ready
    autocron.start('autocron.db')  # activate autocron with his SQLite database
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jens/repos/django-for-runners/.venv/lib/python3.11/site-packages/autocron/__init__.py", line 36, in start
    _engine.start(database_file=database_file, workers=workers)
  File "/home/jens/repos/django-for-runners/.venv/lib/python3.11/site-packages/autocron/engine.py", line 132, in start
    if self.interface.is_worker_pid(pid):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jens/repos/django-for-runners/.venv/lib/python3.11/site-packages/autocron/sqlite_interface.py", line 107, in wrapper
    raise sqlite3.OperationalError(message)
sqlite3.OperationalError: unable to open database file
```

Seems to me, that `autocron.configuration.Configuration._get_autocron_directory()` will be never called! So the used parent directory `~.autocron/` will be not created.

**Comment by kbr** [comment]
In the upcoming 1.1.0 version (see development-branch)  the `configuration` module is no longer present. But it could still be that the `~.autocron/` directory may not get created. Will go into this.

**Comment by jedie** [comment]
Think it's better to store the file as default into `~/.cache/` 

Maybe similar to https://github.com/requests-cache/requests-cache e.g.:
```
session = CachedSession(
    'demo_cache',
    use_cache_dir=True,                # Save files in the default user cache dir
)
```
This will result in the file: `~/.cache/demo_cache.sqlite`

**Comment by kbr** [comment]
Technically `~/.cache/` would just be another path-name, but autocron stores not cached data but callables, payloads, results and also the configuration. On deleting a cache one would assume to lose some performance, but not real data. So from my point of view `~/.autocron/` is the proper place.

**Comment by jedie** [comment]
Maybe also a good option is to use https://pypi.org/project/platformdirs/ and use `user_data_dir` ?

**Comment by kbr** [comment]
Nice project - even know one maintainer. Beside that it is aimed for desktop applications it would end in using one opinionated location in favor of another opinionated location for the price of an additional dependency.
